# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('d68818b97a24c50fca37d0ae37fc8071_ODc2MzMyMDEyLTA1LTA2IDE3OjUwOjM3LjUwMTQ3NQ')
  end)
end
